<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submit</name>
   <tag></tag>
   <elementGuidId>44a34d26-fbe0-4608-93cf-1ed5b97fa412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form//child::*[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form//child::*[@type='submit']</value>
      <webElementGuid>03a156e7-72ed-4784-b88d-4fd9cc0fb86d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
