<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_telp</name>
   <tag></tag>
   <elementGuidId>cb183e04-9f32-459f-bb0a-232881936948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form//child::*[@type='tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form//child::*[@type='tel']</value>
      <webElementGuid>2ff88450-c326-44bc-93d4-af464b6b0e4e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
