<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_password</name>
   <tag></tag>
   <elementGuidId>3f4c6699-9990-4985-ba04-d15021079a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//form//child::*[@type='password'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//form//child::*[@type='password'])[1]</value>
      <webElementGuid>4a179bcd-e64a-43f4-aaaf-2576a41cefad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
