<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_dob</name>
   <tag></tag>
   <elementGuidId>f6fbe611-ffd1-4cbb-be83-ab3bb3e57c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='dob']//child::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='dob']//child::input</value>
      <webElementGuid>1161f0df-8456-4305-a96f-35e523edb70a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
